### ISSUE TITLE
Set up flask backend

### ISSUE THREAD

**Issue by emilysaeli** [emilysaeli/back-end-inspiration-board#1]

**Comment by sarah-kw** [comment]
Setup complete -- to pull changes:

Pull from git
Create local postgres DB inspiration_board_development
Create .env file with FLASK_ENV=development
SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@localhost:5432/inspiration_board_development
install venv, requirements.txt
run flask db upgrade
